Repository csiddu/Frontend-Treasure, pull requests merged in 2023-10, with the labels that each got.

#10 LoginAdded
  Login page/image/view.jpg
  Login page/login.html
  Login page/style2.css
Labels: hactoberfest

#18 Search List added for components
  components.html
  script.js
Labels: enhancement, hacktoberfest-accepted

#20 Contact form updated
  components/contact_form/index.html
Labels: enhancement, hacktoberfest-accepted

#21 added components.json
  README.md
  components.html
  components.json
  components/Login_page/index.html
  images/view.jpg
  script.js
Labels: documentation, enhancement, hacktoberfest-accepted

#22 i add a new style for the footer
  index.html
Labels: enhancement, hactoberfest
